# Instalar librerías

In [1]:
!pip install numpy

# Importar librerías a utilizar en este libro

In [1]:
import numpy

In [2]:
lista=[1,2,3]

In [3]:
type(lista)

list

Crear una matriz a partir de una lista (unidimensional)

In [4]:
matriz=numpy.array(lista) #Forma uno de crear una matriz

In [5]:
type(matriz)

numpy.ndarray

In [6]:
matriz

array([1, 2, 3])

In [7]:
import numpy as np

In [8]:
matriz2=np.array(lista)

In [9]:
matriz2

array([1, 2, 3])

In [10]:
matriz.ndim

1

In [11]:
matriz.shape

(3,)

In [12]:
lista3=[1.0,True,"a",3]

In [13]:
matriz3=np.array(lista3)

In [14]:
matriz3

array(['1.0', 'True', 'a', '3'], dtype='<U32')

In [15]:
print(matriz3.dtype)

<U32


In [16]:
print(matriz2.dtype)

int32


## Las matrices sólo pueden tener un tipo de dato

In [17]:
matriz4=np.array([1,2,3], dtype="float") #Segunda manera de crear una matriz (Escribir dentro de np.array)

In [18]:
matriz4

array([1., 2., 3.])

In [19]:
matriz4.dtype

dtype('float64')

In [20]:
matriz5=np.array([1,2,3], dtype="float16")

In [21]:
matriz5.dtype

dtype('float16')

# Operaciones con matrices

## Crear listas

In [22]:
m=[1,2,3]
n=[3,4,5]

In [23]:
m+n #Al sumar dos listas las coloca una detrás de otra

[1, 2, 3, 3, 4, 5]

In [24]:
matriz_m=np.array(m)
matriz_n=np.array(n)

In [25]:
matriz_m+matriz_n

array([4, 6, 8])

In [26]:
# Matriz tiene índices [a,b,c]

In [27]:
np.square(matriz_m)

array([1, 4, 9], dtype=int32)

In [28]:
matriz_m[0]

1

In [29]:
matriz_m[-1]

3

In [30]:
matriz_m[-3]

1

In [31]:
matriz_m[0] = True

In [32]:
matriz_m

array([1, 2, 3])

In [33]:
matriz_m[1] = True

In [34]:
matriz_m

array([1, 1, 3])

In [35]:
matriz_m[0]= "abc"

ValueError: invalid literal for int() with base 10: 'abc'

In [36]:
matriz_o=np.array([6,7,8,9])

In [37]:
matriz_o

array([6, 7, 8, 9])

In [38]:
matriz_m

array([1, 1, 3])

In [39]:
matriz_m+matriz_o

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [40]:
matriz_negativos=matriz_m-matriz_n

In [41]:
np.absolute(matriz_negativos)

array([2, 3, 2])

In [42]:
np.maximum(matriz_m,matriz_n)

array([3, 4, 5])

In [43]:
np.minimum(matriz_m,matriz_n)

array([1, 1, 3])

In [44]:
np.maximum(matriz_m,matriz_o)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [45]:
matriz_m

array([1, 1, 3])

In [46]:
matriz_m.sort()
matriz_m

array([1, 1, 3])

In [47]:
matriz_m.sort()
matriz_m

array([1, 1, 3])

## Ejercicio

# Lunes

### Matrices bidimensionales

In [48]:
bidim=np.array([[18,23,20],[400,380,710]])

In [49]:
bidim

array([[ 18,  23,  20],
       [400, 380, 710]])

In [50]:
bidim.shape #Dimensiones de la matriz

(2, 3)

In [51]:
bidim.ndim #Cuántas n dimensiones posee?

2

In [52]:
bidim[-1,-1]

710

In [53]:
bidim[0,0]

18

In [54]:
np.resize(bidim,(10,10))

array([[ 18,  23,  20, 400, 380, 710,  18,  23,  20, 400],
       [380, 710,  18,  23,  20, 400, 380, 710,  18,  23],
       [ 20, 400, 380, 710,  18,  23,  20, 400, 380, 710],
       [ 18,  23,  20, 400, 380, 710,  18,  23,  20, 400],
       [380, 710,  18,  23,  20, 400, 380, 710,  18,  23],
       [ 20, 400, 380, 710,  18,  23,  20, 400, 380, 710],
       [ 18,  23,  20, 400, 380, 710,  18,  23,  20, 400],
       [380, 710,  18,  23,  20, 400, 380, 710,  18,  23],
       [ 20, 400, 380, 710,  18,  23,  20, 400, 380, 710],
       [ 18,  23,  20, 400, 380, 710,  18,  23,  20, 400]])

In [58]:
f=np.arange(1,16,7) # MAtriz de a(1) hasta b-1(16-1=15) con una diferencia de 7
f

array([ 1,  8, 15])

In [60]:
g=np.arange(1,10) #Matriz de a hasta b-1
g

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
gg= np.array([g,g])
gg

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [62]:
h=np.reshape(np.array(range(1,26)),(5,5))
h

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [63]:
i=np.asarray([1,2,3])
i

array([1, 2, 3])

In [64]:
i.dtype

dtype('int32')

In [65]:
j=i.astype("complex64") #Cambiar tipo de datos a complex

In [66]:
j.dtype

dtype('complex64')

In [67]:
j

array([1.+0.j, 2.+0.j, 3.+0.j], dtype=complex64)

In [68]:
k=i.astype("float64") #Cambiar a float

In [69]:
k

array([1., 2., 3.])

In [70]:
k.dtype

dtype('float64')

In [71]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [72]:
np.eye(10, dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [73]:
np.eye(2,3) #Por defecto la matriz tiene decimales

array([[1., 0., 0.],
       [0., 1., 0.]])

In [74]:
np.eye(2,3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.]])

In [75]:
np.eye(10,7, k=3, dtype=int)

array([[0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [76]:
#numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)

In [78]:
np.eye(N=10,M=7,k=3)

array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [79]:
np.eye(N=7, M=10, k=3)

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [80]:
np.zeros(3) #Matriz de 0s

array([0., 0., 0.])

In [81]:
np.ones(shape=(2,3)) #Matriz de 1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [82]:
np.empty(shape=(3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 8.08291397e-321],
       [2.46151512e-312, 2.00485144e-307, 0.00000000e+000]])

In [83]:
np.full(shape=(2,8), fill_value=False)

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [84]:
np.identity(4) #Siempre 1s en diagonal principal y siempre cuadradas

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [85]:
import numpy as np

In [90]:
a=np.random.randint(1,20,10)

In [91]:
a

array([ 9,  3, 15,  1, 15, 10,  6, 10, 15, 17])